### ISSUE TITLE
boost::posix_time::ptime visualizer fails on Visual Studio 2017

### ISSUE THREAD

**Issue by aligature** [KindDragon/CPPDebuggerVisualizers#10]
Fails with:
Natvis: C:\USERS\WEBBERA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_F83E6E1A\EXTENSIONS\JRPEI2XO.WNX\Visualizers\boost_DateTime.natvis(31,23): Error: Expression is too long or complex to be supported by the debugger.

**Comment by aligature** [comment]
Also see https://connect.microsoft.com/VisualStudio/feedback/details/3131078/debug-visualizers-for-boost-posix-time-ptime-fail

**Comment by KindDragon** [comment]
Should work now https://marketplace.visualstudio.com/items?itemName=ArkadyShapkin.CDebuggerVisualizersforVS2017

**Comment by aligature** [comment]
That's awesome. Did you actually find the Intrinsic element referenced in any natvis documentation? I've never seen it and it's the exact tool I was wishing existed.

**Comment by KindDragon** [comment]
I found Intrinsic element description in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Xml\Schemas\1033\natvis.xsd" and their examples of use 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Packages\Debugger\Visualizers\stl.natvis"
