### ISSUE TITLE
Boost::multi_index

### ISSUE THREAD

**Issue by SergeyVSB** [KindDragon/CPPDebuggerVisualizers#13]
Seems, that somebody have an idea about it
http://cpp-russia.ru/?p=1422#more-1422

If it is possible, may be boost::property_tree is possible too?

**Comment by a-tokar** [comment]
Hi,
I'm the author of that talk. You can check out the final solution here: https://github.com/a-tokar/BoostMultiIndexNatvis. Using it, you can write visualizer for `boost::property_tree`. I checked that it works.

**Comment by SergeyVSB** [comment]
Hi,
Tested your visualizer. Based on it, I've got interesting results for boost::property_tree. I'll make PR with ptree visualizer here soon. Will you make PR with multiindex visualizers or should I do it?

**Comment by a-tokar** [comment]
Hey,
I think, I can add both `multi_index` and `property_tree` at once.

**Comment by SergeyVSB** [comment]
Can you wait a little? I don't know what exactly I want from property_tree. It requires special view of multi_index and I need some more experiments.i will write you in one or two days.19.11.2017, 21:32, "Anton Tokar" <notifications@github.com>:Hey,
I think, I can add both multi_index and property_tree at once.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С уважением, СергейBest regards, Sergey

**Comment by a-tokar** [comment]
Sure, no hurry at all. You can ask me, if you have any questions. I can provide you my version of `boost::ptree` visualizer.

**Comment by KindDragon** [comment]
@a-tokar Hi. Do you mind if I add your visualizers to my extension?

**Comment by KindDragon** [comment]
Thanks. Fixed in 1.0.20
