### ISSUE TITLE
vs2015 update3 can’t view boost shared_ptr

### ISSUE THREAD

**Issue by boostiewj** [KindDragon/CPPDebuggerVisualizers#14]
vs2015 update3,Win10,can’t view boost shared_ptr
vs2017 is ok

**Comment by boostiewj** [comment]
boost 1.64

**Comment by KindDragon** [comment]
Version 1.0.20 should fix this issue https://marketplace.visualstudio.com/items?itemName=ArkadyShapkin.CDebuggerVisualizersforVS2015#overview
