### ISSUE TITLE
Boost container changes

### ISSUE THREAD

**Issue by arthur-tacca** [KindDragon/CPPDebuggerVisualizers#20]
boost::container has (at least) two changes from 1.66 to 1.67:

* The namespace `boost::container::container_detail` has been renamed to `boost::container::dtl` throughout (in boostorg/container@fa24946).
* The class `vector_alloc_holder` has moved out of `boost::container::container_detail` altogether into `boost::container` (in boostorg/container@2802a1f).

The second change broke the visualiser for `vector`, and also `flat_map` and `flat_set` (which use `vector` internally). The first change probably broke all containers! Sorry this isn't a pull request :-( but I thought a hint would be better than nothing.

**Comment by KindDragon** [comment]
Resolved for VS2019
