### ISSUE TITLE
No preview for boost::none

### ISSUE THREAD

**Issue by haferburg** [KindDragon/CPPDebuggerVisualizers#23]
I'm seeing the following error when trying to preview a `boost::optional<>` that is initialized to `boost::none`.

    Natvis: C:\USERS\AHAFERBU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_854067BE\EXTENSIONS\0O1HEMU5.ZR2\Visualizers\boost.natvis(106,2): Warning: Unable to load a visualized preview for type 'boost::optional<std::pair<bool,bool> >' because the conditions of all <DisplayString> elements were false.

My suggestion would be to change it to 

    <Type Name="boost::optional&lt;*&gt;" Priority="Medium">
        <AlternativeType Name="boost::optional_detail::optional_base&lt;*&gt;" />
        <DisplayString Condition="m_initialized">{m_storage}</DisplayString>
        <DisplayString Condition="!m_initialized">boost::none</DisplayString>
        <Expand>
            <Item Condition="m_initialized" Name="value">m_storage</Item>
        </Expand>
    </Type>

**Comment by KindDragon** [comment]
Resolved in PR #27
