### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by BenKenobi85** [KindDragon/CPPDebuggerVisualizers#26]
Happy user for older VS versions.
Is there any plan to add support for the current Visual Studio 2019?

**Comment by ByronFaber** [comment]
Seconded.   haven't had time to look at updating it myself, you can just snag the .natvis files out of the code and drop them into a directory listed here:   https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019

**Comment by BenKenobi85** [comment]
Great hint, works fine for VS2019 16.2.0 Preview 2.0 (put the .natvis files of the .vsix package into 
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Packages\Debugger\Visualizers)

Thanks a lot!
