### ISSUE TITLE
VS2019 support

### ISSUE THREAD

**Issue by ymiroshnyk** [KindDragon/CPPDebuggerVisualizers#28]
Hi.

It would be nice to have an extension with visualizers for VS2019.

Thanks.

**Comment by dmenendez-gruposantander** [comment]
I've manually downloaded some .natvis files and they work as-is for VS2019 (e.g. visualizers for Boost.Optional and Boost.Variant).

I don't know what extra work is necessary to publish the extension for VS2019.
